// <auto-generated />
using FileManager.FileManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileManagerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FileManager.FileManagerApi.Models.FileModel", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderModelName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderModelPath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepositoryModelName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepositoryModelPath")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Path", "Name");

                    b.HasIndex("FolderModelPath", "FolderModelName");

                    b.HasIndex("RepositoryModelPath", "RepositoryModelName");

                    b.ToTable("FileModel");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.FolderModel", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderModelName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderModelPath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepositoryModelName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepositoryModelPath")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Path", "Name");

                    b.HasIndex("FolderModelPath", "FolderModelName");

                    b.HasIndex("RepositoryModelPath", "RepositoryModelName");

                    b.ToTable("FolderModel");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.RepositoryModel", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserModelUsername")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Path", "Name");

                    b.HasIndex("UserModelUsername");

                    b.ToTable("RepositoryModel");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.UserModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.FileModel", b =>
                {
                    b.HasOne("FileManager.FileManagerApi.Models.FolderModel", null)
                        .WithMany("Files")
                        .HasForeignKey("FolderModelPath", "FolderModelName");

                    b.HasOne("FileManager.FileManagerApi.Models.RepositoryModel", null)
                        .WithMany("Files")
                        .HasForeignKey("RepositoryModelPath", "RepositoryModelName");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.FolderModel", b =>
                {
                    b.HasOne("FileManager.FileManagerApi.Models.FolderModel", null)
                        .WithMany("Folders")
                        .HasForeignKey("FolderModelPath", "FolderModelName");

                    b.HasOne("FileManager.FileManagerApi.Models.RepositoryModel", null)
                        .WithMany("Folders")
                        .HasForeignKey("RepositoryModelPath", "RepositoryModelName");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.RepositoryModel", b =>
                {
                    b.HasOne("FileManager.FileManagerApi.Models.UserModel", null)
                        .WithMany("Repositories")
                        .HasForeignKey("UserModelUsername");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.FolderModel", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.RepositoryModel", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("FileManager.FileManagerApi.Models.UserModel", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
